### ISSUE TITLE
Delete one of the quiz page components

### ISSUE THREAD

**Issue by RehasLiamsi** [AgilWebProjekt/AgilProjekt#22]
There are two quiz page components at the moment. One is in the src folder, and the other is in the components folder. Can you take a look a delete one of them?

**Comment by wassimtajeddin** [comment]
Yes, I can. Thanks for reminding me.

**Comment by wassimtajeddin** [comment]
I had to push the changes directly to the main branch. Otherwise, it won't be deleted.
